version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=zY51ZTzVVTGitWkwWnft82ndvDXWSlrBdIPTqY9A
      - ZONE=timostroehlein.com
      #- SUBDOMAIN=subdomain
      - PROXIED=true
